add_lunch_combo du_clark-userdebug
add_lunch_combo du_d802-userdebug
add_lunch_combo du_h815-userdebug
add_lunch_combo du_lux-userdebug
add_lunch_combo du_oneplus2-userdebug
add_lunch_combo du_oneplus3-userdebug
add_lunch_combo du_osprey-userdebug
add_lunch_combo du_pme-userdebug
