add_lunch_combo du_cheeseburger-userdebug
add_lunch_combo du_clark-userdebug
add_lunch_combo du_d802-userdebug
add_lunch_combo du_lux-userdebug
add_lunch_combo du_oneplus3-userdebug
add_lunch_combo du_osprey-userdebug
add_lunch_combo du_pme-userdebug
add_lunch_combo du_x2-userdebug
