add_lunch_combo du_bacon-userdebug
add_lunch_combo du_clark-userdebug
add_lunch_combo du_ether-userdebug
add_lunch_combo du_h815-userdebug
add_lunch_combo du_lux-userdebug
add_lunch_combo du_m8-userdebug
add_lunch_combo du_oneplus3-userdebug
add_lunch_combo du_Z00T-userdebug
