add_lunch_combo du_deb-userdebug
add_lunch_combo du_flo-userdebug
add_lunch_combo du_grouper-userdebug
add_lunch_combo du_hammerhead-userdebug
add_lunch_combo du_mako-userdebug
add_lunch_combo du_shamu-userdebug
