add_lunch_combo du_angler-userdebug
add_lunch_combo du_bullhead-userdebug
add_lunch_combo du_dragon-userdebug
add_lunch_combo du_hammerhead-userdebug
add_lunch_combo du_marlin-userdebug
add_lunch_combo du_sailfish-userdebug
add_lunch_combo du_shamu-userdebug
