#!/system/bin/sh

. /system/etc/init.d.cfg
. $script_helpers

if [ "x$battery" = "xtrue" ];
then
echo "1000" > /proc/sys/vm/dirty_expire_centisecs;
echo "2000" > /proc/sys/vm/dirty_writeback_centisecs
fi
