#!/system/bin/sh

. /system/etc/init.d.cfg
. $script_helpers

if [ "x$gpurender" = "xtrue" ];
then
sysrw
rm /system/lib/egl/libGLES_android.so
busybox sed -i '/0 0 android/d' /system/lib/egl/egl.cfg
sysro
fi
