#!/system/bin/sh

. /system/etc/init.d.cfg
. $script_helpers

if [ "x$file_system_speedups" = "xtrue" ];
then
	busybox mount -o remount,noatime,barrier=0,nobh /system
	busybox mount -o remount,noatime /data
	busybox mount -o remount,noatime,barrier=0,nobh /cache
fi
